In [1]:
# This is notebook cover some of the fundamentals of TensorFlow

#INtroduction to Tensors

In [2]:
#Import Tensorflow
import tensorflow as tf
print(tf.__version__ )

2.18.0


In [3]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#Check the number of dimensions of a tensor(ndim stands for number for dimensions)
scalar.ndim

0

In [7]:
#Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
#Check the dimension. of vector
vector.ndim

1

In [9]:
#Create a matrix(has more than 1 dimesion)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
matrix.ndim

2

In [11]:
#Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]],dtype=tf.float16) #Specifiy the data type with dytpe parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>