In [24]:
# This is notebook cover some of the fundamentals of TensorFlow

#INtroduction to Tensors

In [25]:
#Import Tensorflow
import tensorflow as tf
print(tf.__version__ )

2.18.0


In [26]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [27]:
#Check the number of dimensions of a tensor(ndim stands for number for dimensions)
scalar.ndim #Scalar have no dimension you can see in output

0

In [28]:
#Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [29]:
#Check the dimension. of vector
vector.ndim #Vector have one dimension you can see in output

1

In [30]:
#Create a matrix(has more than 1 dimesion)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [31]:
matrix.ndim #Matrix have two dimension you can see in output

2

In [32]:
#Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]],dtype=tf.float16) #Specifiy the data type with dytpe parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [33]:
#What is the number of dimension of another_matrix
another_matrix.ndim

2

In [35]:
# Create a tensor
tensor = tf.constant([[[1,2,3],
                     [4,5,6]],
                     [[7,8,9],
                     [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [36]:
tensor.ndim

3

#What we have created so far
-Scalar: a single number
- Vector: a number with direction(e.g wind speed and direction)
- Matrix: a 2-dimensional array of numbers
- Tensor: an n-dimensional array of numbers(when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

# Creating tensors with 'tf.Variable'


In [40]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [41]:
#Create the name tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>